### ISSUE TITLE
Runtime error -> jwt (Spring) 

### ISSUE THREAD

**Issue by carstenroesner** [ralscha/blog#7]
After solving an "no available storage method found" error by installing

```
ionic cordova plugin add cordova-sqlite-storage
npm install --save @ionic/storage
```

and modifying your imports (IonicStorageModule.forRoot()) in app.module.ts to

 ```
   imports: [
            BrowserModule,
            HttpModule,
            IonicModule.forRoot(MyApp),
            IonicStorageModule.forRoot(),
            CustomFormsModule
        ],
```
"ionic serve" started without any error. 

But after every login oder signup execution, I get a runtime error and "finally()" 
is reported as a non-existant function ?!

There's no error or warning in Atom or Visual Studio Code.

```
TypeError: this.authProvider.login(...).finally is not a function
    at LoginPage.webpackJsonp.385.LoginPage.login (http://192.168.0.101:8100/build/main.js:148:21)
    at Object.eval [as handleEvent] (ng:///AppModule/LoginPage.ngfactory.js:69:31)
    at handleEvent (http://192.168.0.101:8100/build/vendor.js:12696:138)
    at callWithDebugContext (http://192.168.0.101:8100/build/vendor.js:14160:42)
    at Object.debugHandleEvent [as handleEvent] (http://192.168.0.101:8100/build/vendor.js:13748:12)
    at dispatchEvent (http://192.168.0.101:8100/build/vendor.js:9289:21)
    at http://192.168.0.101:8100/build/vendor.js:11457:20
    at SafeSubscriber.schedulerFn [as _next] (http://192.168.0.101:8100/build/vendor.js:4321:36)
    at SafeSubscriber.__tryOrUnsub (http://192.168.0.101:8100/build/vendor.js:33379:16)
    at SafeSubscriber.next (http://192.168.0.101:8100/build/vendor.js:33326:22)

```
What did I miss, where's my mistake?

**Comment by ralscha** [comment]
Hi
Thanks for the feedback. I can reproduce the error. The problem is that finally needs to be imported like all the other rxjs operators
```
import "rxjs/add/operator/finally";
```
Don't know why this worked before

**Comment by carstenroesner** [comment]
Hi,

thank you for your immediate resonse. I added the import and login oder signup execution works perfectly well now! 
Thank you.
